# Generated by Django 2.2.4 on 2020-04-05 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0004_auto_20200405_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_text', models.TextField(verbose_name='Текст жалобы')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_author', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался')),
                ('complain_flat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_flat', to='property.Flat', verbose_name='Квартира, на которую пожаловались')),
            ],
        ),
    ]
