# Generated by Django 2.2.4 on 2020-04-05 15:57

from django.db import migrations
import phonenumbers

def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all():
        parsed_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        normalized_phone = phonenumbers.format_number(parsed_phone, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
        flat.owner_phone_pure = normalized_phone
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_phone_pure'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers),
    ]
