# Generated by Django 2.2.4 on 2020-04-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(related_name='flat_owner', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
