# Generated by Django 2.2.4 on 2020-04-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20200405_1926'),
    ]

    operations = [
    ]
