# Generated by Django 2.2.4 on 2020-04-05 19:40

from django.db import migrations


def migrate_owner_data(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")

    for flat in Flat.objects.all():
        obj, changed = Owner.objects.get_or_create(owner_name=flat.owner,
                                            owners_phonenumber=flat.owners_phonenumber,
                                            owner_phone_pure=flat.owner_phone_pure)
        obj.flats.add(flat)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20200405_1955'),
    ]

    operations = [
        migrations.RunPython(migrate_owner_data),
    ]
