# Generated by Django 2.2.4 on 2020-04-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20200405_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='Flat',
            name='owners_phonenumber',
        ),
        migrations.RemoveField(
            model_name='Flat',
            name='owner_phone_pure',
        ),
    ]
